#!/usr/bin/env python3
"""
Generate short AI intro clips for AI Learning Hub lessons with a text-to-video model.

Supported providers (you bring your own API key):
  - veo     Google Veo via the Gemini API   (env: GEMINI_API_KEY)      pip install google-genai
  - sora    OpenAI Sora via the Videos API   (env: OPENAI_API_KEY)      pip install openai
  - runway  Runway Gen-4/4.5 via Runway API  (env: RUNWAYML_API_SECRET) pip install runwayml requests

What it does:
  1. Reads prompts.json  (key = "<moduleId>/<lessonId>")
  2. Calls the chosen provider, polls until the clip is ready
  3. Saves it to  ../public/videos/<moduleId>-<lessonId>.mp4
  4. Rewrites ../src/data/generatedVideos.js so the app shows the clip automatically

Examples:
  python generate.py --provider veo
  python generate.py --provider sora --only dl/what --only genai/llms
  python generate.py --provider runway --only python/intro

NOTE: these APIs cost money and the exact SDK surface changes over time.
The veo path is the reference implementation; for sora/runway, check the current
docs if a field name has changed. Costs are roughly: Veo ~$0.40-0.75/sec,
Sora and Runway priced per second/credit as well — generate a few, not all, first.
"""
import argparse
import json
import pathlib
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parent
APP = ROOT.parent
VIDEO_DIR = APP / "public" / "videos"
DATA_FILE = APP / "src" / "data" / "generatedVideos.js"
PROMPTS_FILE = ROOT / "prompts.json"


def safe_name(key: str) -> str:
    return key.replace("/", "-")


def load_prompts() -> dict:
    data = json.loads(PROMPTS_FILE.read_text(encoding="utf-8"))
    return {k: v for k, v in data.items() if not k.startswith("_")}


# ----------------------------- providers -----------------------------

def gen_veo(prompt: str, out_path: pathlib.Path, *, model: str, aspect: str, resolution: str):
    from google import genai
    from google.genai import types

    client = genai.Client()  # reads GEMINI_API_KEY
    op = client.models.generate_videos(
        model=model,  # e.g. "veo-3.1-fast-generate-preview"
        prompt=prompt,
        config=types.GenerateVideosConfig(aspect_ratio=aspect, resolution=resolution),
    )
    while not op.done:
        time.sleep(15)
        op = client.operations.get(op)
    video = op.response.generated_videos[0].video
    client.files.download(file=video)
    video.save(str(out_path))


def gen_sora(prompt: str, out_path: pathlib.Path, *, model: str, seconds: int, size: str):
    from openai import OpenAI

    client = OpenAI()  # reads OPENAI_API_KEY
    job = client.videos.create(model=model, prompt=prompt, seconds=str(seconds), size=size)
    terminal = {"completed", "failed"}
    while job.status not in terminal:
        time.sleep(15)
        job = client.videos.retrieve(job.id)
    if job.status != "completed":
        raise RuntimeError(f"Sora job {job.id} ended with status: {job.status}")
    # Download the rendered MP4
    content = client.videos.download_content(job.id, variant="video")
    content.write_to_file(str(out_path))


def gen_runway(prompt: str, out_path: pathlib.Path, *, model: str, duration: int, ratio: str):
    import requests
    from runwayml import RunwayML

    client = RunwayML()  # reads RUNWAYML_API_SECRET
    task = client.text_to_video.create(
        model=model,            # e.g. "gen4_turbo"
        prompt_text=prompt,
        duration=duration,
        ratio=ratio,            # e.g. "1280:720"
    )
    terminal = {"SUCCEEDED", "FAILED"}
    while True:
        t = client.tasks.retrieve(task.id)
        if t.status in terminal:
            break
        time.sleep(10)
    if t.status != "SUCCEEDED":
        raise RuntimeError(f"Runway task {task.id} ended with status: {t.status}")
    url = t.output[0]
    out_path.write_bytes(requests.get(url, timeout=120).content)


# ----------------------------- manifest -----------------------------

def rebuild_manifest(prompts: dict):
    """Scan the videos folder and write a {key: '/videos/...'} map the app reads."""
    mapping = {}
    for key in prompts:
        f = VIDEO_DIR / f"{safe_name(key)}.mp4"
        if f.exists() and f.stat().st_size > 0:
            mapping[key] = f"/videos/{safe_name(key)}.mp4"

    body = ",\n".join(f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in sorted(mapping.items()))
    js = (
        "// AUTO-GENERATED by video-gen/generate.py — do not edit by hand.\n"
        "// Maps '<moduleId>/<lessonId>' to a generated MP4 in /public/videos.\n"
        "// The Module page prefers a generated clip over the curated YouTube video.\n"
        f"export default {{\n{body}{',' if body else ''}\n}}\n"
    )
    DATA_FILE.write_text(js, encoding="utf-8")
    print(f"\nManifest updated: {len(mapping)} clip(s) -> {DATA_FILE.relative_to(APP)}")


# ----------------------------- main -----------------------------

def main():
    ap = argparse.ArgumentParser(description="Generate AI intro clips for lessons.")
    ap.add_argument("--provider", choices=["veo", "sora", "runway"], default="veo")
    ap.add_argument("--only", action="append", default=[],
                    help="Generate only this key (repeatable), e.g. --only dl/what")
    ap.add_argument("--duration", type=int, default=8, help="Clip length in seconds (provider limits apply)")
    # provider-specific knobs with sensible defaults
    ap.add_argument("--veo-model", default="veo-3.1-fast-generate-preview")
    ap.add_argument("--veo-resolution", default="720p")
    ap.add_argument("--sora-model", default="sora-2")
    ap.add_argument("--sora-size", default="1280x720")
    ap.add_argument("--runway-model", default="gen4_turbo")
    ap.add_argument("--runway-ratio", default="1280:720")
    args = ap.parse_args()

    prompts = load_prompts()
    keys = args.only or list(prompts)
    missing = [k for k in keys if k not in prompts]
    if missing:
        sys.exit(f"Unknown prompt key(s): {missing}. Available: {list(prompts)}")

    VIDEO_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Provider: {args.provider} | clips: {len(keys)} | output: {VIDEO_DIR.relative_to(APP)}\n")

    for i, key in enumerate(keys, 1):
        spec = prompts[key]
        out = VIDEO_DIR / f"{safe_name(key)}.mp4"
        aspect = spec.get("aspect", "16:9")
        print(f"[{i}/{len(keys)}] {key}  ({spec.get('title', '')})")
        print(f"    prompt: {spec['prompt'][:90]}...")
        try:
            if args.provider == "veo":
                gen_veo(spec["prompt"], out, model=args.veo_model,
                        aspect=aspect, resolution=args.veo_resolution)
            elif args.provider == "sora":
                gen_sora(spec["prompt"], out, model=args.sora_model,
                         seconds=args.duration, size=args.sora_size)
            else:
                ratio = args.runway_ratio if aspect == "16:9" else "720:1280"
                gen_runway(spec["prompt"], out, model=args.runway_model,
                           duration=args.duration, ratio=ratio)
            print(f"    saved -> {out.relative_to(APP)}\n")
        except Exception as e:  # keep going; report at the end
            print(f"    FAILED: {e}\n")

    rebuild_manifest(prompts)
    print("Done. Run the app (npm run dev) and open a module — generated clips show at the top of the lesson.")


if __name__ == "__main__":
    main()
